# Benchmark 3: Medium Model Configuration
# ~8M parameters - Balanced performance

model:
  model_type: "gpt_encoder"
  vocab_size: 50257
  d_model: 256
  n_layer: 6
  n_head: 8
  d_ff: 1024
  max_seq_len: 128
  p_drop: 0.1

training:
  epochs: 50
  batch_size: 8
  learning_rate: 0.0005
  weight_decay: 0.01
  warmup_steps: 500
  max_grad_norm: 1.0
  save_interval: 10
  eval_interval: 5
  log_interval: 50
  device: "cuda"
  mixed_precision: true
  gradient_accumulation_steps: 2

data:
  seq_len: 128
  num_workers: 4
