# Benchmark 9: Mini GPT Large Configuration
# ~65M parameters - Large mini GPT variant

model:
  model_type: "mini_gpt"
  vocab_size: 50257
  d_model: 512
  n_layer: 8
  n_head: 8
  d_ff: 2048
  max_seq_len: 64
  p_drop: 0.1

training:
  epochs: 90
  batch_size: 4
  learning_rate: 0.0003
  weight_decay: 0.01
  warmup_steps: 900
  max_grad_norm: 1.0
  save_interval: 18
  eval_interval: 6
  log_interval: 90
  device: "cuda"
  mixed_precision: true
  gradient_accumulation_steps: 4
  seed: 42
  early_stopping_patience: 10
  early_stopping_min_delta: 0.001

data:
  seq_len: 64
  num_workers: 4
