# Benchmark 8: Mini GPT Medium Configuration
# ~35M parameters - Medium mini GPT variant

model:
  model_type: "mini_gpt"
  vocab_size: 50257
  d_model: 448
  n_layer: 7
  n_head: 7
  d_ff: 1792
  max_seq_len: 64
  p_drop: 0.1

training:
  epochs: 60
  batch_size: 5
  learning_rate: 0.0004
  weight_decay: 0.01
  warmup_steps: 600
  max_grad_norm: 1.0
  save_interval: 12
  eval_interval: 5
  log_interval: 60
  device: "cuda"
  mixed_precision: true
  gradient_accumulation_steps: 3
  seed: 42
  early_stopping_patience: 10
  early_stopping_min_delta: 0.001

data:
  seq_len: 64
  num_workers: 4
