# Benchmark 2: Small Model Configuration
# ~1M parameters - Efficient baseline

model:
  model_type: "gpt_encoder"
  vocab_size: 50257
  d_model: 128
  n_layer: 4
  n_head: 4
  d_ff: 512
  max_seq_len: 64
  p_drop: 0.1

training:
  epochs: 25
  batch_size: 16
  learning_rate: 0.0008
  weight_decay: 0.01
  warmup_steps: 200
  max_grad_norm: 1.0
  save_interval: 5
  eval_interval: 2
  log_interval: 25
  device: "cuda"
  mixed_precision: true
  gradient_accumulation_steps: 1
  seed: 42

data:
  seq_len: 64
  num_workers: 4
